#184637233 Set up an empty Express Boilerplate with dotenv
atlp-rwanda/falcons-ec-be pull request #1
Opened 2023-03-07 18:34 UTC by masterchief-00

#### What does this PR do?

- Creates a boilerplate for the project
- added dotenv configuration

#### Description of Task to be completed?
 Set up an empty Express Boilerplate with dotenv
#### How should this be manually tested?
 clone the project and use the terminal to start the development server by "npm run dev"
#### Any background context you want to provide?
 none
#### What are the relevant pivotal tracker/Trello stories?
 Tracker: 184637233
#### Screenshots (if appropriate)
 none
#### Questions:
 none

2023-03-07 18:39 UTC, kirengaboris approved these changes

2023-03-07 18:42 UTC, fab-ryan commented on .env.example
> +PORT=<port number>
you need to add new line after

2023-03-07 18:43 UTC, fab-ryan commented on src/helpers/helperFn.js
> +*/
adding new line here

2023-03-07 18:45 UTC, fab-ryan commented on src/validations/validation.js
> +*/
leave new here

2023-03-07 18:45 UTC, fab-ryan requested changes
check those comments

2023-03-07 19:34 UTC, masterchief-00 commented on .env.example
> +PORT=<port number>
done

2023-03-07 19:34 UTC, masterchief-00 commented on src/helpers/helperFn.js
> +*/
done

2023-03-07 19:34 UTC, masterchief-00 commented on src/validations/validation.js
> +*/
done

2023-03-07 19:46 UTC, fab-ryan approved these changes

2023-03-07 20:30 UTC, denislohan requested changes
commit message do not make much sense becae they are verbose. too much long. I ma expecting shorter description

chore (): setup an empty express boilerplate
You can leave the () empty as it is not active over a single file/folder

2023-03-08 07:01 UTC, masterchief-00 commented
> commit message do not make much sense becae they are verbose. too much long. I ma expecting shorter description
> 
> chore (): setup an empty express boilerplate You can leave the () empty as it is not active over a single file/folder

I have edited the commit message

2023-03-08 07:03 UTC, fab-ryan commented
then squash commits

2023-03-08 07:13 UTC, masterchief-00 commented
> then squash commits

I think they are squashed because I did the "git rebase -i HEAD~3" and now **git log** shows one commit

2023-03-08 07:15 UTC, fab-ryan commented
that means you only have more than 3 header
check again

2023-03-08 07:33 UTC, fab-ryan approved these changes

2023-03-08 08:44 UTC, denislohan requested changes
We need only one Commit, or maximum 2

2023-03-08 10:12 UTC, denislohan approved these changes

2023-03-08 10:16 UTC, merged