#184637249  log into the E-commerce application via email & password
atlp-rwanda/falcons-ec-be pull request #16
Opened 2023-03-17 16:01 UTC by kirengaboris

### What does this PR do?
- Login a user via email and password
### Description of Task to be completed?
- Create a route for logging in as a user with a password and email
### How should this be manually tested?
- Clone this project run the script "npm run dev" then run this URL in the browser http://localhost:5000/api-docs
### Any background context you want to provide?
- N/A
### What are the relevant pivotal tracker/Trello stories?
- Tracker: 184637249
### Screenshots (if appropriate)
- N/A
### Questions:
- N/A

2023-03-17 16:56 UTC, masterchief-00 approved these changes

2023-03-17 16:58 UTC, dean-daryl approved these changes

2023-03-19 18:26 UTC, fab-ryan requested changes
why I don't see any documentation on this endpoint

2023-03-19 18:55 UTC, fab-ryan approved these changes

2023-03-19 18:56 UTC, merged