#184637234 Configure The App to use PostgreSQL as DB Engine and Sequelize ORM
atlp-rwanda/falcons-ec-be pull request #2
Opened 2023-03-08 10:15 UTC by masterchief-00

#### What does this PR do?

- Configures the project to use postgrSQL as the database and Sequelize ORM

#### Description of Task to be completed?
- Configure The App to use PostgreSQL as DB Engine and Sequelize ORM
#### How should this be manually tested?
 - clone the project and use the terminal to start the development server by "npm run dev"
 - make sure that you have PostgreSQL installed
 - create a database and
 - then use the database name and password to make the DEV_DATABASE_URL in your env file,
 - refer to the env.example file
#### Any background context you want to provide?
 none
#### What are the relevant pivotal tracker/Trello stories?
 Tracker: 184637234
#### Screenshots (if appropriate)
 none
#### Questions:
 none

2023-03-08 10:32 UTC, fab-ryan commented on .babelrc
> +  }
please remember to put new line at the end

2023-03-08 10:35 UTC, fab-ryan commented on src/config/database.js
> +export const sequelize = new Sequelize(process.env.DEV_DATABASE_URL, {
you have config file then again you are calling env, use config file to determine node environment

2023-03-08 10:36 UTC, fab-ryan commented on src/models/index.js
> +  sequelize = new Sequelize(process.env[config.use_env_variable], config);
referencing to this

2023-03-08 10:36 UTC, fab-ryan commented on server.js
> +app.use("/users", dummyRoutes);
you can combine all routes and calling it here once

2023-03-08 10:37 UTC, fab-ryan requested changes
work to those comments

2023-03-08 12:07 UTC, fab-ryan commented on index.js
>  });
what???

2023-03-08 12:08 UTC, fab-ryan commented on src/config/database.js
> +export const sequelize = new Sequelize(process.env.DEV_DATABASE_URL, {
you didn't change it?

2023-03-08 13:45 UTC, fab-ryan approved these changes

2023-03-08 13:55 UTC, kirengaboris approved these changes

2023-03-08 14:46 UTC, denislohan commented
@masterchief-00 , also set up the babel for es6

2023-03-08 14:48 UTC, istafrica-dennw requested changes
1. Add babel
2. your commit?? named how?? rename it t follow conventions

2023-03-09 09:31 UTC, fab-ryan commented on src/middlewares/middleware.js
> + */
remove those unnecessary line

2023-03-09 09:32 UTC, fab-ryan commented on src/models/User.js
> +};
remember this at every time

2023-03-09 09:33 UTC, fab-ryan commented on src/controllers/dummyController.js
> +import db from "../models/index.js";
it seems you haven't configured  babel well

2023-03-09 10:30 UTC, fab-ryan approved these changes

2023-03-09 11:37 UTC, masterchief-00 commented
> 1. Add babel
> 2. your commit?? named how?? rename it t follow conventions

It's all done

2023-03-09 13:01 UTC, denislohan approved these changes

2023-03-09 13:07 UTC, merged