#184637252 Reset user password via email
atlp-rwanda/falcons-ec-be pull request #21
Opened 2023-03-22 12:36 UTC by rwamugema

### What does this PR do?

Given a user forgets the password for his/her account:

1. Should be able to make a request to reset the password.
2. Should receive an email containing a link to reset the password.

### Description of Task to be completed?

 * Design an endpoint and a controller to receive the request from the user and send an email with `link` to reset the password. 
 * Design an endpoint and a controller to verify and reset user password.

### How should this be manually tested?

**Installation**

**1. Clone the repository by running**

`git clone https://github.com/atlp-rwanda/falcons-ec-be.git
`
**2. Navigate to the project directory by running cd falcons-ec-be.**

`cd falcons-ec-be`

**5. Install the necessary dependencies by running npm install.**

`npm install`

6. **Run the development server by running npm run dev. This will start the server using Nodemon, which will automatically reload the server when changes are made to the code.**

`npm run dev`

7. **Run the tests by running npm run test**

`npm run test`

### Any background context you want to provide?

when running this on local server put into consideration the below information 👇

  * Add the the user log in token in headers with a key of `Authorization `and make sure that the value is started by `Bearer
`
* Add the token generated when reset password made into parameters of the endpoint  `PATCH:/api/v1/users/:token`

 * For making a request to reset password ,use endpoint POST: /api/v1/users/password
 * for making a reset password process, use endpoint PATCH:/api/v1/users/:token
 
kindly consider adding request body in this format while making a request to reset the password:

```
{
"email":"youremail@example.com",
}
```

kindly consider adding request body in this format while reseting the  password:
```
{
"password":"12345"
}

```
### What are the relevant pivotal tracker/Trello stories?

Tracker: 184637252

### Screenshots (if appropriate)

none

### Questions:

none

2023-03-27 14:39 UTC, dean-daryl approved these changes

2023-03-28 11:50 UTC, fab-ryan commented on src/controllers/userController.js
> +    });
use helper function to send and getting message

2023-03-28 11:51 UTC, fab-ryan requested changes
do requested changes

2023-03-30 09:40 UTC, kirengaboris approved these changes

2023-03-30 09:48 UTC, fab-ryan commented on src/helpers/sendMessage.js
> +  try {
use meaningful variable because we will have a lot of sending messages variables

2023-03-30 09:48 UTC, fab-ryan requested changes
do that request and I will merged it

2023-03-30 10:36 UTC, fab-ryan approved these changes

2023-03-30 10:44 UTC, merged