bg():Fixed category issues
atlp-rwanda/falcons-ec-be pull request #25
Opened 2023-03-23 17:48 UTC by dean-daryl

### **What does this PR do?**
Create/Add Product

###  **Description of Task to be completed?**
A seller should be able to go on our site and create a new product with name, category, description, quantity, price and a minimum of 4 images and a maximum of 8 images .If the product already exists, then he will be asked to increase the stock instead.

### **How should this be manually tested?**
clone the project and use the terminal to start the development server by "npm run dev"
run on localhost:5000

### **Any background context you want to provide?**
none

### **What are the relevant pivotal tracker/Trello stories?**
Tracker: 184637259

**### Screenshots (if appropriate)**
none

### **Questions:**
none

2023-03-23 18:01 UTC, kirengaboris approved these changes

2023-03-23 18:35 UTC, masterchief-00 approved these changes

2023-03-24 12:34 UTC, fab-ryan commented on src/database/migrations/20230323161904-remove-category-name-from-Products.js
> +    });
this should be category_id not categoryName

2023-03-24 12:34 UTC, fab-ryan commented on src/swagger.json
> -                  "description": "The category of the new product."
same as here

2023-03-24 12:35 UTC, fab-ryan requested changes
naming is wrong

2023-03-27 10:54 UTC, fab-ryan approved these changes

2023-03-27 11:26 UTC, merged