#184693444 account verification
atlp-rwanda/falcons-ec-be pull request #27
Opened 2023-03-24 15:31 UTC by ingabireclec

### What does this PR do?
- Verify user account after registration
### Description of Task to be completed?
- Verify user account after registration by sending an email to a new account containing verification link 
### How should this be manually tested?
- Clone this project run the script "npm run dev" then run this URL in the browser http://localhost:5000/api-docs
### Any background context you want to provide?
- N/A
### What are the relevant pivotal tracker/Trello stories?
- Tracker: 184693444 
### Screenshots (if appropriate)
- N/A
### Questions:
- N/A

2023-03-28 09:47 UTC, rwamugema reviewed
You can use Eslint to minimize this hound violations.

2023-03-28 11:48 UTC, fab-ryan commented on src/controllers/userController.js
> +
why can't use this as helper function because we will need to send email at any time use it and I think it's here

2023-03-28 11:49 UTC, fab-ryan requested changes
in Email send use Helper functions

2023-03-31 07:24 UTC, fab-ryan commented on src/controllers/userController.js
>      return res.status(500).jsonp({
Jsonp ??? did you json

2023-03-31 07:49 UTC, ingabireclec commented on src/controllers/userController.js
>      return res.status(500).jsonp({
that must have been a typo

2023-03-31 08:14 UTC, fab-ryan commented on src/controllers/userController.js
>      return res.status(500).jsonp({
resolve it

2023-03-31 09:04 UTC, dean-daryl approved these changes

2023-03-31 09:08 UTC, rwamugema approved these changes

2023-03-31 09:14 UTC, fab-ryan approved these changes

2023-03-31 09:14 UTC, merged