#184637248 logout functionality
atlp-rwanda/falcons-ec-be pull request #30
Opened 2023-03-27 13:26 UTC by Jmukakalisa

**What does this PR do?**

This PR adds a feature that allows user to logout once the api is invoked
**Description of Task to be completed?**

The logout feature enables users to safely sign out of the application or website, guaranteeing that their data is safeguarded against unauthorized access.

**How should this be manually tested?**

- clone the repository
- checkout ft-logout-functionality-184637248 branch
- Run npm install to install the dependencies and dev dependencies in your terminal
- Run npm run dev to start the server in terminal and check if server is working
- In URL field enter localhost:PORT/api-docs to open swagger UI
- Login users using /api/v1/users/signin endpoint
- Logout users using /api/v1/users/logout endpoint

**Any background context you want to provide?**
none
**What are the relevant pivotal tracker/Trello stories?**
tracker : #184637248
**Screenshots (if appropriate)**
none
**Questions:**
none

2023-03-27 17:44 UTC, masterchief-00 approved these changes

2023-03-28 11:45 UTC, fab-ryan approved these changes

2023-03-28 11:56 UTC, dean-daryl approved these changes

2023-03-28 12:24 UTC, denislohan requested changes

2023-03-28 12:24 UTC, istafrica-dennw commented on src/middleware/authMiddleware.js
> +          return res.status(500).json({
@Jmukakalisa ,
You need to use the tight status code, 401 (unauthorized) not 500.

2023-03-29 08:35 UTC, istafrica-dennw approved these changes

2023-03-29 09:08 UTC, merged