#184637267 #184637268 #184637269 #184637270 Cart CRUD
atlp-rwanda/falcons-ec-be pull request #39
Opened 2023-04-02 21:31 UTC by dean-daryl

#### What does this PR do?

- Cart CRUD

#### Description of Task to be completed?

Users (buyers) can add to their cart  which is then stored in a session , they can also get items in their cart and finally they can clear their cart.

#### How should this be manually tested?
- clone the repo and run npm run dev in your terminal
- go to localhost:5000/api-docs 
- test the operations of the cart 
#### Any background context you want to provide?
None
#### What are the relevant pivotal tracker/Trello stories?
 Tracker: 184637267 184637268 184637269 184637270
#### Screenshots (if appropriate)
 none
#### Questions:
 none

2023-04-02 21:38 UTC, fab-ryan commented on src/controllers/cartController.js
> +    console.log(decodedData);
Remove this console.log

2023-04-03 06:34 UTC, masterchief-00 approved these changes

2023-04-03 09:16 UTC, kirengaboris approved these changes

2023-04-03 09:36 UTC, denislohan requested changes

2023-04-03 09:36 UTC, denislohan commented on src/database/migrations/20230401145629-add-column-pasword-status.js
> +    await queryInterface.addColumn('Users', 'PasswordStatus', {
1. why is this is plural? are other fields in plural?
2. isn't this a boolean? then it is named wrong, it should be passwordExpired

2023-04-03 09:38 UTC, denislohan reviewed
also your PR is named wrong

2023-04-05 08:33 UTC, fab-ryan approved these changes

2023-04-05 14:35 UTC, istafrica-dennw approved these changes

2023-04-05 15:14 UTC, merged