#184637261 ft update/delete product 184637261
atlp-rwanda/falcons-ec-be pull request #43
Opened 2023-04-06 18:18 UTC by Jmukakalisa

**What does this PR do?**

This PR adds a feature that allows sellers to to mark product available/unavailable in their collection

**Description of Task to be completed?**
A seller should be able to update & delete a specific item from their collection

How should this be manually tested?

- clone the repository
- checkout ft-ft-update/delete-product-184637261
- Run npm install to install the dependencies and dev dependencies in your terminal
- Run npm run dev to start the server in terminal and check if server is working
- In URL field enter localhost:PORT/api-docs to open swagger UI
- Login users using /api/v1/users/signin endpoint
- Verify your toke with otp at /api/v1/users/otp/verify/{token} endpoint
- Authorize /api/v1/products/{id} using your verified token in the authorization key
- update a product available/unavailable using /api/v1/products/{id} endpoint
- delete a product available/unavailable using /api/v1/products/{id}/delete endpoint

**Any background context you want to provide?**
none
**What are the relevant pivotal tracker/Trello stories?**
tracker : #184637261
Screenshots (if appropriate)
none
Questions:
none

2023-04-06 18:23 UTC, dean-daryl approved these changes

2023-04-06 19:18 UTC, masterchief-00 approved these changes

2023-04-10 14:00 UTC, fab-ryan commented on src/controllers/productController.js
> +      return res.status(400).json({ status: 400, success: false, message: 'Product not found' });
404 status not 400

2023-04-10 14:00 UTC, fab-ryan commented on src/controllers/productController.js
> +        message: 'No data provided',
same as here

2023-04-10 14:01 UTC, fab-ryan commented on src/controllers/productController.js
> +      return res.status(400).json({ status: 400, success: false, message: 'Product not found in your collection!' });
please check all status codes if are correct

2023-04-10 14:03 UTC, fab-ryan commented on src/controllers/productController.js
> +    }
I'm afraid that's not right you updating the product before saving the image first save the image then use returned  imageLink and update it in db if it's there

2023-04-10 14:05 UTC, fab-ryan commented on src/controllers/productController.js
> +    }
and remember links are array or json format

2023-04-10 14:06 UTC, fab-ryan requested changes
work on those comments then you will inform me after

2023-04-11 14:07 UTC, closed without merging