ft(recommend): get recommended products to a buyer
atlp-rwanda/falcons-ec-be pull request #89
Opened 2023-06-16 10:51 UTC by rwamugema

### What does this pr do?

Provide recommended products to a buyer basing on there browsing behavior or purchasing history.

### Description of Task to be completed?
Design an endpoint to get recommended products to a buyer.

### How should this be manually tested?
Clone the repository.
install necessary dependencies by running npm install
Hit endpoint products/recommend

### Any background context you want to provide?
This endpoint is restricted to a buyer only.

What are the relevant pivotal tracker stories?
N/A

### Screenshots (if appropriate)

N/A

### Questions.

2023-06-18 19:23 UTC, masterchief-00 approved these changes

2023-06-19 07:04 UTC, dean-daryl approved these changes

2023-06-19 08:36 UTC, fab-ryan commented on src/tests/recommended.js
> +// });
why this test hav been commented?? we need test

2023-06-19 08:42 UTC, fab-ryan requested changes
No test here please provide those tests

2023-06-19 10:56 UTC, fab-ryan approved these changes

2023-06-19 10:57 UTC, merged